// <auto-generated />
using System;
using Foundation.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Foundation.Infrastructure.Migrations;

[DbContext(typeof(FoundationDbContext))]
partial class FoundationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Foundation.Domain.Entities.Employee", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Email")
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnType("character varying(250)");

            b.Property<string>("FirstName")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("LastName")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("Role")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            b.HasKey("Id");

            b.ToTable("Employees");
        });

        modelBuilder.Entity("Foundation.Domain.Entities.Skill", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<int>("Category")
                .HasColumnType("integer");

            b.Property<bool>("IsActive")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasDefaultValue(true);

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<Guid?>("ParentSkillId")
                .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("ParentSkillId");

            b.HasIndex(new[] { "Name", "Category", "ParentSkillId" }, "IX_Skills_Name_Category_ParentSkillId")
                .IsUnique();

            b.ToTable("Skills");
        });

        modelBuilder.Entity("Foundation.Domain.Entities.Skill", b =>
        {
            b.HasOne("Foundation.Domain.Entities.Skill", "ParentSkill")
                .WithMany("ChildSkills")
                .HasForeignKey("ParentSkillId")
                .OnDelete(DeleteBehavior.Restrict);

            b.Navigation("ParentSkill");
        });

        modelBuilder.Entity("Foundation.Domain.Entities.Skill", b =>
        {
            b.Navigation("ChildSkills");
        });
#pragma warning restore 612, 618
    }
}
